export const products = [
  {
    id: 1,
    title: "iPhone 16 Pro",
    price: 1250,
    category: "smartphone",
    brand: "Apple",
    stock: 12,
    rating: 4.9,
    isAvailable: true,
    tags: ["phone", "premium", "apple"],
  },
  {
    id: 2,
    title: "Samsung Galaxy S25",
    price: 950,
    category: "smartphone",
    brand: "Samsung",
    stock: 8,
    rating: 4.7,
    isAvailable: true,
    tags: ["phone", "android"],
  },
  {
    id: 3,
    title: "MacBook Air M4",
    price: 1400,
    category: "laptop",
    brand: "Apple",
    stock: 5,
    rating: 4.8,
    isAvailable: true,
    tags: ["laptop", "work"],
  },
  {
    id: 4,
    title: "AirPods Pro 2",
    price: 250,
    category: "accessory",
    brand: "Apple",
    stock: 0,
    rating: 4.6,
    isAvailable: false,
    tags: ["audio", "wireless"],
  },
  {
    id: 5,
    title: "Redmi Note 14",
    price: 220,
    category: "smartphone",
    brand: "Xiaomi",
    stock: 25,
    rating: 4.3,
    isAvailable: true,
    tags: ["phone", "budget"],
  },
];
